version: '3'

services:
  postegres-db:
    image: postgres:latest
    container_name: postgres-server
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=alumno
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=course-db
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  sql-db:
    image: mysql:latest
    container_name: mysql-server
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=course-db
      - MYSQL_USER=alumno
      - MYSQL_PASSWORD=123456
    volumes:
      - ./volumes/mysql:/var/lib/mysql
