server:
  port: 8091

spring:
  application:
    name: msvc-course-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/course-db
    username: alumno
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/